---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: payment_webservices
  description: Payment back-end
  tags:
    - java
    - springboot
  links:
    - url: https://www.gravitee.io/
      title: gravitee configuration page
spec:
  type: service
  lifecycle: production
  owner: team-payment-1
  dependsOn: [payment-lib]
  # providesApis: [TODO]
  # consumesApis: [messaging-api]
  system: Payment
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: payment-lib
  description: a lib with all the low level payment operations
  tags:
    - java
    - jsp
  links:
    - url: https://mvnrepository.com/
      title: maven Repository page
spec:
  type: library
  lifecycle: production
  owner: team-payment-2
  subcomponentOf: payment_webservices
  system: Payment
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: inventory-catalog
  description: webservices used to search ressources in the inventory
  tags:
    - java
    - quarkus
  links:
    - url: https://www.gravitee.io/
      title: gravitee configuration page
spec:
  type: service
  lifecycle: production
  # dependsOn: [TODO]
  # providesApis: [TODO]
  # consumesApis: [messaging]
  owner: team-inventory-1
  system: Inventory
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: inventory-admin
  description: inventory administration UI
  tags:
    - flash
  links:
    - url: https://www.adobe.com/fr/products/flashplayer/end-of-life-alternative.html
      title: website
spec:
  type: website
  lifecycle: deprecated
  owner: team-inventory-1
  # dependsOn: [TODO]
  # providesApis: [TODO]
  # consumesApis: [inventory-catalog]
  system: Inventory
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: vendor-mobile
  description: market place mobile application
  tags:
    - flutter
  links:
    - url: https://play.google.com/
      title: google playstore app page
spec:
  type: website
  lifecycle: experimental
  owner: team-vendor-1
  # dependsOn: [TODO]
  # providesApis: [TODO]
  # consumesApis: [inventory-catalog-api,payment_api]
  system: Vendor
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: vendor-front
  description: market place front application
  tags:
    - react
  links:
    - url: https://react.dev/
      title: public url
spec:
  type: website
  lifecycle: production
  owner: team-vendor-1
  # dependsOn: [TODO]
  # providesApis: [TODO]
  # consumesApis: [inventory-catalog-api,payment_api]
  system: Vendor
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: messaging
  description: Messaging platform (KAFKA)
  tags:
    - kafka
  links:
    - url: https://kafka.apache.org/20/documentation.html
      title: Apache Kafka documentaion
spec:
  type: service
  lifecycle: production
  owner: team-vendor-1
  # dependsOn: [TODO]
  # providesApis: [TODO]
  # consumesApis: [TODO]
  system: Vendor
