---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-user
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: guest
spec:
  memberOf: [guests]
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-group
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: guests
  description: The group referencing all the guest users
  links:
    - url: https://slack.com/
      title: Slack chanel
      icon: message
spec:
  type: root
  profile:
    displayName: Guests
    email: gests@example.com
    picture: https://cdn.pixabay.com/photo/2018/03/21/06/30/community-3245739_1280.png
  children: []
---
# Practice Group tree
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: Practices
  description: The root group of the practices groups
  links:
    - url: https://slack.com/
      title: Slack chanel
      icon: message
spec:
  type: root
  profile:
    displayName: Practices
    email: practrices@example.com
    picture: https://api.dicebear.com/6.x/initials/svg?seed=Pratices
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: Software
  description: The group referencing all the users and groups with software skills
  links:
    - url: https://slack.com/
      title: Slack chanel
      icon: message
spec:
  type: team
  profile:
    displayName: Software
    email: software@example.com
    picture: https://api.dicebear.com/6.x/initials/svg?seed=Software
  children: []
  parent: Practices
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: Architecture
  description: The group referencing all the users and groups with sofware architecture activities
  links:
    - url: https://slack.com/
      title: Slack chanel
      icon: message
spec:
  type: team
  profile:
    displayName: Architecture
    email: architecture@example.com
    picture: https://api.dicebear.com/6.x/initials/svg?seed=Architecture
  children: []
  parent: Software
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: Backend
  description: The group referencing all the users and groups with backend development skills
  links:
    - url: https://slack.com/
      title: Slack chanel
      icon: message
spec:
  type: team
  profile:
    displayName: Backend Development
    email: backend@example.com
    picture: https://api.dicebear.com/6.x/initials/svg?seed=Backend
  children: []
  parent: Software
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: JAVA
  description: Java User Group
  links:
    - url: https://slack.com/
      title: Slack chanel
      icon: message
spec:
  type: team
  profile:
    displayName: JAVA
    email: java@example.com
    picture: https://api.dicebear.com/6.x/initials/svg?seed=JAVA
  children: []
  parent: Backend
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: Kafka
  description: The group referencing all the users and groups with Microsoft Kafka skills
  links:
    - url: https://slack.com/
      title: Slack chanel
      icon: message
spec:
  type: team
  profile:
    displayName: Kafka
    email: Kafka@example.com
    picture: https://api.dicebear.com/6.x/initials/svg?seed=Kafka
  children: []
  parent: Backend
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: NodeJS
  description: The group referencing all the users and groups with Microsoft .NET backend development skills
  links:
    - url: https://slack.com/
      title: Slack chanel
      icon: message
spec:
  type: team
  profile:
    displayName: NodeJS
    email: nodejs@example.com
    picture: https://api.dicebear.com/6.x/initials/svg?seed=NodeJS
  children: []
  parent: Backend
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: Frontend
  description: The group referencing all the users and groups with frontend development skills
  links:
    - url: https://slack.com/
      title: Slack chanel
      icon: message
spec:
  type: team
  profile:
    displayName: Frontend Development
    email: frontend@example.com
    picture: https://api.dicebear.com/6.x/initials/svg?seed=Frontend
  children: []
  parent: Software
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: Angular
  description: The group referencing all the users and groups with Angular frontend development skills
  links:
    - url: https://slack.com/
      title: Slack chanel
      icon: message
spec:
  type: team
  profile:
    displayName: Angular
    email: angular@example.com
    picture: https://api.dicebear.com/6.x/initials/svg?seed=Angular
  children: []
  parent: Frontend
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: ReactJS
  description: The group referencing all the users and groups with ReactJS frontend development skills
  links:
    - url: https://slack.com/
      title: Slack chanel
      icon: message
spec:
  type: team
  profile:
    displayName: ReactJS
    email: reactjs@example.com
    picture: https://api.dicebear.com/6.x/initials/svg?seed=ReactJS
  children: []
  parent: Frontend
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: DevOps
  description: The group referencing all the users and groups with DevOps skills
  links:
    - url: https://slack.com/
      title: Slack chanel
      icon: message
spec:
  type: team
  profile:
    displayName: DevOps
    email: Dev-Ops@example.com
    picture: https://api.dicebear.com/6.x/initials/svg?seed=DevOps
  children: []
  parent: Software
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: Azure
  description: The group referencing all the users and groups with Azure cloud platform skills
  links:
    - url: https://slack.com/
      title: Slack chanel
      icon: message
spec:
  type: team
  profile:
    displayName: Azure
    email: azure@example.com
    picture: https://api.dicebear.com/6.x/initials/svg?seed=Azure
  children: []
  parent: DevOps
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: Kubernetes
  description: The group referencing all the users and groups with Kubernetes skills
  links:
    - url: https://slack.com/
      title: Slack chanel
      icon: message
spec:
  type: team
  profile:
    displayName: Kubernetes
    email: kubernetes@example.com
    picture: https://api.dicebear.com/6.x/initials/svg?seed=Kubernetes
  children: []
  parent: DevOps
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: Business
  description: The group referencing all the users and groups with tranversal or business activities
  links:
    - url: https://slack.com/
      title: Slack chanel
      icon: message
spec:
  type: team
  profile:
    displayName: Business
    email: business@example.com
    picture: https://api.dicebear.com/6.x/initials/svg?seed=Business
  children: []
  parent: Practices
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: Management
  description: The group referencing all the users and groups with mangement activities
  links:
    - url: https://slack.com/
      title: Slack chanel
      icon: message
spec:
  type: team
  profile:
    displayName: Management
    email: Management@example.com
    picture: https://api.dicebear.com/6.x/initials/svg?seed=Management
  children: []
  parent: Business
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: Lean
  description: The group referencing all the users and groups with  lean mangement skills
  links:
    - url: https://slack.com/
      title: Slack chanel
      icon: message
spec:
  type: team
  profile:
    displayName: Lean
    email: Lean@example.com
    picture: https://api.dicebear.com/6.x/initials/svg?seed=Lean
  children: []
  parent: Management
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: Agile
  description: The group referencing all the users and groups with Agile mangement skills
  links:
    - url: https://slack.com/
      title: Slack chanel
      icon: message
spec:
  type: team
  profile:
    displayName: Agile
    email: agile@example.com
    picture: https://api.dicebear.com/6.x/initials/svg?seed=Agile
  children: []
  parent: Management
---
# Organization Group tree
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: Organization
  description: The root group of the teams constituing the company
  links:
    - url: https://slack.com/
      title: Slack chanel
      icon: message
spec:
  type: root
  profile:
    displayName: Organization
    email: organization@example.com
    picture: https://api.dicebear.com/6.x/initials/svg?seed=Organization
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: Market_Place
  description: The group referencing the teams of the Market place
  links:
    - url: https://slack.com/
      title: Slack chanel
      icon: message
spec:
  type: business-unit
  profile:
    displayName: Market Place
    email: mp@example.com
    picture: https://api.dicebear.com/6.x/initials/svg?seed=
  children: []
  parent: Organization
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: Software_Factory
  description: The group referencing the teams of the software factory unit
  links:
    - url: https://slack.com/
      title: Slack chanel
      icon: message
spec:
  type: product-area
  profile:
    displayName: Software Factory
    email: softFactory@example.com
    picture: https://api.dicebear.com/6.x/initials/svg?seed=Software%20Factory
  children: []
  parent: Market_Place
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: Payment
  description: The group referencing all the teams dedicated to the payment product
  links:
    - url: https://slack.com/
      title: Slack chanel
      icon: message
spec:
  type: product-area
  profile:
    displayName: Payment
    email: payment@example.com
    picture: https://api.dicebear.com/6.x/initials/svg?seed=Payment
  children: []
  parent: Software_Factory
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: team-payment-1
  description: the first team on the payment product
  links:
    - url: https://slack.com/
      title: Slack chanel
      icon: message
spec:
  type: team
  profile:
    displayName: team-payment-1
    email: team-payment-1@example.com
    picture: https://api.dicebear.com/6.x/initials/svg?seed=team%20payment-1
  children: []
  parent: Payment
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: team-payment-2
  description: the first team on the payment product
  links:
    - url: https://slack.com/
      title: Slack chanel
      icon: message
spec:
  type: team
  profile:
    displayName: team-payment-2
    email: team-payment-2@example.com
    picture: https://api.dicebear.com/6.x/initials/svg?seed=team%20payment-2
  children: []
  parent: Payment
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: Vendor
  description: The group referencing all the teams dedicated to the vendor products
  links:
    - url: https://slack.com/
      title: Slack chanel
      icon: message
spec:
  type: product-area
  profile:
    displayName: Vendor
    email: vendor@example.com
    picture: https://api.dicebear.com/6.x/initials/svg?seed=Vendor
  children: []
  parent: Software_Factory
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: team-vendor-1
  description: the first team on the vendor product
  links:
    - url: https://slack.com/
      title: Slack chanel
      icon: message
spec:
  type: team
  profile:
    displayName: team-vendor-1
    email: team-vendor-1@example.com
    picture: https://api.dicebear.com/6.x/initials/svg?seed=team%20vendor-1
  children: []
  parent: Vendor
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: Messaging
  description: The group referencing all the teams dedicated to the Messaging project
  links:
    - url: https://slack.com/
      title: Slack chanel
      icon: message
spec:
  type: product-area
  profile:
    displayName: Messaging
    email: messaging@example.com
    picture: https://api.dicebear.com/6.x/initials/svg?seed=Messaging
  children: []
  parent: Software_Factory
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: team-messaging-1
  description: the first team on the messaging project
  links:
    - url: https://slack.com/
      title: Slack chanel
      icon: message
spec:
  type: team
  profile:
    displayName: team-messaging-1
    email: team-messaging-1@example.com
    picture: https://api.dicebear.com/6.x/initials/svg?seed=team%20messaging-1
  children: []
  parent: Messaging
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: Inventory
  description: The group referencing all the teams dedicated to the Inventory project
  links:
    - url: https://slack.com/
      title: Slack chanel
      icon: message
spec:
  type: product-area
  profile:
    displayName: Inventory
    email: inventory@example.com
    picture: https://api.dicebear.com/6.x/initials/svg?seed=Inventory
  children: []
  parent: Software_Factory
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: team-inventory-1
  description: the first team on the Inventory project
  links:
    - url: https://slack.com/
      title: Slack chanel
      icon: message
spec:
  type: team
  profile:
    displayName: team-inventory-1
    email: team-inventory-1@example.com
    picture: https://api.dicebear.com/6.x/initials/svg?seed=team%20inventory-1
  children: []
  parent: Inventory
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: Infrastructure
  description: The infra department
  links:
    - url: https://slack.com/
      title: Slack chanel
      icon: message
spec:
  type: business-unit
  profile:
    displayName: Infrastructure
    email: infra@example.com
    picture: https://api.dicebear.com/6.x/initials/svg?seed=Infrastructure
  parent: Market_Place
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: Backstage
  description: The backstage sub-department
  links:
    - url: https://slack.com/
      title: Slack chanel
      icon: message
spec:
  type: product-area
  profile:
    displayName: Backstage
    email: backstage@example.com
    picture: https://api.dicebear.com/6.x/initials/svg?seed=Backstage
  parent: Infrastructure
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: team-backstage-1
  description: Team backstage 1
  links:
    - url: https://slack.com/
      title: Slack chanel
      icon: message
spec:
  type: team
  profile:
    displayName: team-backstage-1
    email: team-backstage-1@example.com
    picture: https://api.dicebear.com/6.x/initials/svg?seed=team%20backstage-1
  parent: Backstage
  children: []
